In [1]:
import tensorflow as tf
import sklearn
from sklearn import datasets
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
sklearn.__version__

'1.0.2'

In [3]:
from sklearn.datasets import load_wine
X, y = load_wine(return_X_y = True)

In [5]:
wine = pd.DataFrame(X)

In [6]:
wine.head()

0     1     2     3      4     5     6     7     8     9     10    11  \
0  14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

       12  
0  1065.0  
1  1050.0  
2  1185.0  
3  1480.0  
4   735.0

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
x_train,x_test,y_train,y_test = train_test_split(X, y, test_size = .3 )
x_train.shape, x_test.shape,y_train.shape,y_test.shape

((124, 13), (54, 13), (124,), (54,))

In [9]:
# No need to scale because sklearn already scaled the data

In [10]:
from sklearn.neural_network import MLPClassifier

In [18]:
model = MLPClassifier(hidden_layer_sizes = (20,), max_iter = 10000)
model.fit(x_train, y_train)

MLPClassifier(hidden_layer_sizes=(20,), max_iter=10000)

In [19]:
model.score(x_train, y_train)

0.5967741935483871

In [20]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1])

In [21]:
model.score(x_test, y_test)

0.7037037037037037

In [22]:
model.coefs_

[array([[ 1.05803208e-01, -1.40991244e-01, -2.73864563e-01,
          9.90504698e-03, -3.75566394e-02,  1.05523543e-01,
          4.28590346e-01, -8.90324256e-02,  3.64535747e-01,
          1.94840768e-01,  4.18942853e-02, -2.55529479e-02,
         -2.43663254e-01,  4.05240791e-01, -3.64804065e-01,
         -5.15780180e-02,  1.34521740e-01,  3.22137994e-05,
         -2.66410985e-01,  2.92340878e-01],
        [ 1.15985467e-01,  1.39949459e-01,  1.52455936e-01,
         -2.76135594e-03, -4.20229046e-01, -2.19053213e-01,
          2.73856580e-01, -9.27752090e-02,  3.20857141e-01,
          1.34659207e-01, -2.46741651e-02, -6.94486216e-02,
          7.18712269e-02,  1.25413005e-01,  3.73275728e-01,
          3.82171807e-01, -3.33534023e-01, -1.98998568e-01,
          3.32141797e-01, -1.13143903e-01],
        [-2.24597493e-01,  4.01742932e-01, -1.93774665e-02,
          1.32077813e-01,  9.39811942e-02, -1.44229413e-01,
         -3.18231537e-02, -2.94201069e-01,  2.41218693e-01,
         -2.

In [23]:
model.coefs_[0]

array([[ 1.05803208e-01, -1.40991244e-01, -2.73864563e-01,
         9.90504698e-03, -3.75566394e-02,  1.05523543e-01,
         4.28590346e-01, -8.90324256e-02,  3.64535747e-01,
         1.94840768e-01,  4.18942853e-02, -2.55529479e-02,
        -2.43663254e-01,  4.05240791e-01, -3.64804065e-01,
        -5.15780180e-02,  1.34521740e-01,  3.22137994e-05,
        -2.66410985e-01,  2.92340878e-01],
       [ 1.15985467e-01,  1.39949459e-01,  1.52455936e-01,
        -2.76135594e-03, -4.20229046e-01, -2.19053213e-01,
         2.73856580e-01, -9.27752090e-02,  3.20857141e-01,
         1.34659207e-01, -2.46741651e-02, -6.94486216e-02,
         7.18712269e-02,  1.25413005e-01,  3.73275728e-01,
         3.82171807e-01, -3.33534023e-01, -1.98998568e-01,
         3.32141797e-01, -1.13143903e-01],
       [-2.24597493e-01,  4.01742932e-01, -1.93774665e-02,
         1.32077813e-01,  9.39811942e-02, -1.44229413e-01,
        -3.18231537e-02, -2.94201069e-01,  2.41218693e-01,
        -2.89389748e-01, -2.1

In [24]:
model.coefs_[1]

array([[-0.42191092, -0.37352271, -0.43759463],
       [-0.19321226, -0.09464488, -0.24292515],
       [-0.15975181, -0.21516794, -0.2861191 ],
       [ 0.25036075, -0.13086364,  0.35289264],
       [ 0.27169525, -0.2219327 ,  0.36063634],
       [ 0.4070441 , -0.18194437,  0.31997465],
       [-0.3905808 , -0.03327701, -0.37460805],
       [-0.40818479, -0.4477148 , -0.38808801],
       [-0.42550818, -0.46102332,  0.44877964],
       [ 0.29435752,  0.25985475,  0.05910367],
       [-0.36486933, -0.066819  ,  0.2567343 ],
       [-0.11729083,  0.39904825,  0.43522983],
       [ 0.09896415,  0.2747847 ,  0.44499834],
       [-0.3105786 ,  0.10732471, -0.42149209],
       [ 0.01274575, -0.08449369,  0.46595174],
       [-0.11837873,  0.01303336,  0.25043051],
       [ 0.28134163,  0.00716656, -0.424205  ],
       [ 0.08118917,  0.31731805, -0.32349745],
       [ 0.45783606,  0.33858299,  0.4022516 ],
       [-0.28567631, -0.3934041 ,  0.15989106]])